const nsIDataCall = {
};
const nsIDataCallInterfaceListener = {
};
const nsIDataCallCallback = {
};
const nsIDataCallInterface = {
    DATACALL_FAIL_NONE: 0,
    DATACALL_FAIL_OPERATOR_BARRED: 8,
    DATACALL_FAIL_INSUFFICIENT_RESOURCES: 26,
    DATACALL_FAIL_MISSING_UKNOWN_APN: 27,
    DATACALL_FAIL_UNKNOWN_PDP_ADDRESS_TYPE: 28,
    DATACALL_FAIL_USER_AUTHENTICATION: 29,
    DATACALL_FAIL_ACTIVATION_REJECT_GGSN: 30,
    DATACALL_FAIL_ACTIVATION_REJECT_UNSPECIFIED: 31,
    DATACALL_FAIL_SERVICE_OPTION_NOT_SUPPORTED: 32,
    DATACALL_FAIL_SERVICE_OPTION_NOT_SUBSCRIBED: 33,
    DATACALL_FAIL_SERVICE_OPTION_OUT_OF_ORDER: 34,
    DATACALL_FAIL_NSAPI_IN_USE: 35,
    DATACALL_FAIL_ONLY_IPV4_ALLOWED: 50,
    DATACALL_FAIL_ONLY_IPV6_ALLOWED: 51,
    DATACALL_FAIL_ONLY_SINGLE_BEARER_ALLOWED: 52,
    DATACALL_FAIL_PROTOCOL_ERRORS: 111,
    DATACALL_FAIL_VOICE_REGISTRATION_FAIL: -1,
    DATACALL_FAIL_DATA_REGISTRATION_FAIL: -2,
    DATACALL_FAIL_SIGNAL_LOST: -3,
    DATACALL_FAIL_PREF_RADIO_TECH_CHANGED: -4,
    DATACALL_FAIL_RADIO_POWER_OFF: -5,
    DATACALL_FAIL_TETHERED_CALL_ACTIVE: -6,
    DATACALL_FAIL_ERROR_UNSPECIFIED: 65535,
    DATACALL_STATE_INACTIVE: 0,
    DATACALL_STATE_ACTIVE_DOWN: 1,
    DATACALL_STATE_ACTIVE_UP: 2,
    DATACALL_AUTH_NONE: 0,
    DATACALL_AUTH_PAP: 1,
    DATACALL_AUTH_CHAP: 2,
    DATACALL_AUTH_PAP_OR_CHAP: 3,
    DATACALL_PDP_TYPE_IPV4: 0,
    DATACALL_PDP_TYPE_IPV4V6: 1,
    DATACALL_PDP_TYPE_IPV6: 2,
    DATACALL_DEACTIVATE_NO_REASON: 0,
    DATACALL_DEACTIVATE_RADIO_SHUTDOWN: 1,
};
const nsIDataCallInterfaceService = {
};
