const nsINetworkInfo = {
    NETWORK_STATE_UNKNOWN: -1,
    NETWORK_STATE_CONNECTING: 0,
    NETWORK_STATE_CONNECTED: 1,
    NETWORK_STATE_DISCONNECTING: 2,
    NETWORK_STATE_DISCONNECTED: 3,
    NETWORK_STATE_ENABLED: 4,
    NETWORK_STATE_DISABLED: 5,
    NETWORK_TYPE_UNKNOWN: -1,
    NETWORK_TYPE_WIFI: 0,
    NETWORK_TYPE_MOBILE: 1,
    NETWORK_TYPE_MOBILE_MMS: 2,
    NETWORK_TYPE_MOBILE_SUPL: 3,
    NETWORK_TYPE_WIFI_P2P: 4,
    NETWORK_TYPE_MOBILE_IMS: 5,
    NETWORK_TYPE_MOBILE_DUN: 6,
    NETWORK_TYPE_MOBILE_FOTA: 7,
    NETWORK_TYPE_ETHERNET: 8,
};
const nsINetworkInterface = {
};
