const nsITelephonyListener = {
};
const nsITelephonyCallback = {
};
const nsITelephonyDialCallback = {
};
const nsITelephonyService = {
    CALL_STATE_UNKNOWN: 0,
    CALL_STATE_DIALING: 1,
    CALL_STATE_ALERTING: 2,
    CALL_STATE_CONNECTED: 3,
    CALL_STATE_HELD: 4,
    CALL_STATE_DISCONNECTED: 5,
    CALL_STATE_INCOMING: 6,
    NOTIFICATION_REMOTE_HELD: 0,
    NOTIFICATION_REMOTE_RESUMED: 1,
    CALL_PRESENTATION_ALLOWED: 0,
    CALL_PRESENTATION_RESTRICTED: 1,
    CALL_PRESENTATION_UNKNOWN: 2,
    CALL_PRESENTATION_PAYPHONE: 3,
};
